/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KaasRouteImport } from './routes/kaas'
import { Route as DelicatessenRouteImport } from './routes/delicatessen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BroodjesRouteImport } from './routes/broodjes'
import { Route as BorrelplankenRouteImport } from './routes/borrelplanken'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestellingIdRouteImport } from './routes/bestelling.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KaasRoute = KaasRouteImport.update({
  id: '/kaas',
  path: '/kaas',
  getParentRoute: () => rootRouteImport,
} as any)
const DelicatessenRoute = DelicatessenRouteImport.update({
  id: '/delicatessen',
  path: '/delicatessen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BroodjesRoute = BroodjesRouteImport.update({
  id: '/broodjes',
  path: '/broodjes',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrelplankenRoute = BorrelplankenRouteImport.update({
  id: '/borrelplanken',
  path: '/borrelplanken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellingIdRoute = BestellingIdRouteImport.update({
  id: '/bestelling/$id',
  path: '/bestelling/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/borrelplanken': typeof BorrelplankenRoute
  '/broodjes': typeof BroodjesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delicatessen': typeof DelicatessenRoute
  '/kaas': typeof KaasRoute
  '/menu': typeof MenuRoute
  '/over-ons': typeof OverOnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bestelling/$id': typeof BestellingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/borrelplanken': typeof BorrelplankenRoute
  '/broodjes': typeof BroodjesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delicatessen': typeof DelicatessenRoute
  '/kaas': typeof KaasRoute
  '/menu': typeof MenuRoute
  '/over-ons': typeof OverOnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bestelling/$id': typeof BestellingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/borrelplanken': typeof BorrelplankenRoute
  '/broodjes': typeof BroodjesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delicatessen': typeof DelicatessenRoute
  '/kaas': typeof KaasRoute
  '/menu': typeof MenuRoute
  '/over-ons': typeof OverOnsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/bestelling/$id': typeof BestellingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/borrelplanken'
    | '/broodjes'
    | '/checkout'
    | '/contact'
    | '/delicatessen'
    | '/kaas'
    | '/menu'
    | '/over-ons'
    | '/admin'
    | '/bestelling/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/borrelplanken'
    | '/broodjes'
    | '/checkout'
    | '/contact'
    | '/delicatessen'
    | '/kaas'
    | '/menu'
    | '/over-ons'
    | '/admin'
    | '/bestelling/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/borrelplanken'
    | '/broodjes'
    | '/checkout'
    | '/contact'
    | '/delicatessen'
    | '/kaas'
    | '/menu'
    | '/over-ons'
    | '/_authenticated/admin'
    | '/bestelling/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BorrelplankenRoute: typeof BorrelplankenRoute
  BroodjesRoute: typeof BroodjesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DelicatessenRoute: typeof DelicatessenRoute
  KaasRoute: typeof KaasRoute
  MenuRoute: typeof MenuRoute
  OverOnsRoute: typeof OverOnsRoute
  BestellingIdRoute: typeof BestellingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaas': {
      id: '/kaas'
      path: '/kaas'
      fullPath: '/kaas'
      preLoaderRoute: typeof KaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delicatessen': {
      id: '/delicatessen'
      path: '/delicatessen'
      fullPath: '/delicatessen'
      preLoaderRoute: typeof DelicatessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broodjes': {
      id: '/broodjes'
      path: '/broodjes'
      fullPath: '/broodjes'
      preLoaderRoute: typeof BroodjesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrelplanken': {
      id: '/borrelplanken'
      path: '/borrelplanken'
      fullPath: '/borrelplanken'
      preLoaderRoute: typeof BorrelplankenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestelling/$id': {
      id: '/bestelling/$id'
      path: '/bestelling/$id'
      fullPath: '/bestelling/$id'
      preLoaderRoute: typeof BestellingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BorrelplankenRoute: BorrelplankenRoute,
  BroodjesRoute: BroodjesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DelicatessenRoute: DelicatessenRoute,
  KaasRoute: KaasRoute,
  MenuRoute: MenuRoute,
  OverOnsRoute: OverOnsRoute,
  BestellingIdRoute: BestellingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
